name: Deploy Python app to Azure Web App - FaceRecognitionAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y build-essential cmake \
          libopenblas-dev liblapack-dev \
          libx11-dev libgtk-3-dev \
          libboost-python-dev python3-dev

      - name: Install Python dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D3CC0C103B874B6EAB2EAFDC2C2E79F0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0E6F3EE8C391455481E3A1294D0C16DF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74EE5CCE0F994172A1E2F7F7419F2402 }}
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'FaceRecognitionAPI' # Replace with your Azure Web App name
          slot-name: 'Production'
